# Generated by Django 4.1 on 2022-10-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_is_owner_profile_email_verified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="email_verified", new_name="is_owner",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_customer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
