# Generated by Django 4.1 on 2022-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_email_verified_profile_is_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BranchName", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
