# Generated by Django 4.1 on 2022-10-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_servicesnameandprrice"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServicesNameAndPrrice", new_name="ServicesNameAndPrice",
        ),
    ]
