# Generated by Django 4.1 on 2022-10-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_rename_servicesnameandprrice_servicesnameandprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicesnameandprice", old_name="Name", new_name="ServiceName",
        ),
    ]
