# Generated by Django 4.1 on 2022-10-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_instructor_age_instructor_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="Gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                max_length=100,
                null=True,
            ),
        ),
    ]
