# Generated by Django 4.1 on 2022-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_instructor_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="Experience",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
