# Generated by Django 4.1 on 2022-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_instructor_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesNameAndPriceOfDirectApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ServiceName", models.CharField(max_length=100, null=True)),
                ("amount", models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
