# Generated by Django 4.1 on 2022-11-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_servicesnameandpriceofdirectapplication"),
    ]

    operations = [
        migrations.DeleteModel(name="ServicesNameAndPriceOfDirectApplication",),
    ]
