# Generated by Django 4.1 on 2022-10-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0006_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=100, null=True)),
                ("LastName", models.CharField(max_length=100, null=True)),
                ("DateOfBirth", models.DateField()),
                (
                    "Gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Phone1", models.CharField(max_length=100, null=True)),
                ("Phone2", models.CharField(max_length=100, null=True)),
                (
                    "BranchId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.branch"
                    ),
                ),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
