# Generated by Django 4.1 on 2022-10-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_branch"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrivingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.CharField(max_length=100, null=True)),
                ("amount", models.PositiveBigIntegerField(null=True)),
                ("TotalHours", models.FloatField(null=True)),
                ("CompletedHours", models.FloatField(default=0)),
                (
                    "BranchId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.branch"
                    ),
                ),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customerdetails",
                    ),
                ),
            ],
        ),
    ]
