# Generated by Django 4.1 on 2022-10-08 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_drivingapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedLicence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LicenceType", models.CharField(max_length=30, null=True)),
                ("LicenceNumber", models.CharField(max_length=40, null=True)),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customerdetails",
                    ),
                ),
            ],
        ),
    ]
