# Generated by Django 4.1 on 2022-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_serviceapplication_customerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceapplication",
            name="AgeProof",
            field=models.ImageField(default="", editable=False, upload_to="AgeProof"),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="ApplicationOfPSV",
            field=models.ImageField(
                default="", editable=False, upload_to="PSVapplication"
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="DrivingLicenseOld",
            field=models.ImageField(
                default="", editable=False, upload_to="DrivinLicenseOld"
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="IdProof",
            field=models.ImageField(default="", editable=False, upload_to="IdProof"),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="MedicalCirtifict",
            field=models.ImageField(
                default="", editable=False, upload_to="MedicalCirtifict"
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="Photo",
            field=models.ImageField(default="", editable=False, upload_to="Photo"),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="PhysicalFitness",
            field=models.ImageField(
                default="", editable=False, upload_to="PhysicalFitness"
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="SchoolCirtifict",
            field=models.ImageField(
                default="", editable=False, upload_to="SchoolCirtifict"
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="Status",
            field=models.CharField(default="", editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="VehicleRegistration",
            field=models.ImageField(default="", editable=False, upload_to="RCbook"),
        ),
        migrations.AlterField(
            model_name="serviceapplication",
            name="SSLC",
            field=models.ImageField(default="", editable=False, upload_to="ssleImages"),
        ),
    ]
