# Generated by Django 4.1 on 2022-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceapplication",
            name="SSLC",
            field=models.ImageField(null=True, upload_to="ssleImages"),
        ),
    ]
