# Generated by Django 4.1 on 2022-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_serviceapplication_ageproof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule", name="time", field=models.TimeField(),
        ),
    ]
