# Generated by Django 4.1 on 2022-10-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0006_branch"),
        ("customer", "0011_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branchName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.branch"
                    ),
                ),
                (
                    "customerName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
