# Generated by Django 4.1 on 2022-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_alter_customerdetails_dateofbirth"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceapplication",
            name="ServiceName",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
