# Generated by Django 4.1 on 2022-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0019_alter_serviceapplication_ageproof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceapplication",
            name="Status",
            field=models.CharField(default="Pending", max_length=100, null=True),
        ),
    ]
