# Generated by Django 4.1 on 2022-10-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_studylicencenameandprice"),
        ("customer", "0020_alter_serviceapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdetails",
            name="DrivingPackage",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.studylicencenameandprice",
            ),
        ),
    ]
