# Generated by Django 4.1 on 2022-10-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0022_customerdetails_createddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discription",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
