# Generated by Django 4.1 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0023_payment_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="driveRelated",
            field=models.BooleanField(null=True),
        ),
    ]
