# Generated by Django 4.1 on 2022-10-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0024_payment_driverelated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="driveRelated",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
