# Generated by Django 4.1 on 2022-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0025_alter_payment_driverelated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdetails",
            name="address",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
