# Generated by Django 4.1 on 2022-11-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0028_serviceapplication_date_serviceapplication_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedServiceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learningDate", models.DateField(default=False, null=True)),
                ("serviceDate", models.DateField(default=False, null=True)),
                (
                    "serviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.serviceapplication",
                    ),
                ),
            ],
        ),
    ]
