# Generated by Django 4.1 on 2022-11-02 00:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0029_appliedserviceschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedserviceschedule",
            name="serviceId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.serviceapplication",
            ),
        ),
        migrations.AlterField(
            model_name="serviceapplication",
            name="Date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="serviceapplication",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
