# Generated by Django 4.1 on 2022-11-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0031_balanceandadvance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balanceandadvance",
            name="CustomerId",
            field=models.OneToOneField(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
