# Generated by Django 4.1 on 2022-11-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0032_alter_balanceandadvance_customerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrivingStudyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TotalHours", models.FloatField(null=True)),
                ("CompletedHours", models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="schedule", old_name="UserId", new_name="drivingApplication",
        ),
        migrations.RemoveField(model_name="schedule", name="BranchId",),
        migrations.AddField(
            model_name="customerdetails",
            name="CompletedHours",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customerdetails",
            name="TotalHours",
            field=models.FloatField(default=10, null=True),
        ),
        migrations.DeleteModel(name="DrivingApplication",),
        migrations.AddField(
            model_name="drivingstudydetails",
            name="DrivingCustomer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customerdetails",
            ),
        ),
    ]
