# Generated by Django 4.1 on 2022-11-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0033_drivingstudydetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="drivingApplication",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customerdetails",
            ),
        ),
    ]
