# Generated by Django 4.1 on 2022-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0034_alter_schedule_drivingapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="Status",
            field=models.CharField(
                choices=[("Up Coming", "Up Coming"), ("Complete", "Complete")],
                default="Up Coming",
                max_length=20,
                null=True,
            ),
        ),
    ]
