# Generated by Django 4.1 on 2022-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0035_schedule_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceapplication",
            name="learnigdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="testDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
