# Generated by Django 4.1 on 2022-11-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0037_serviceapplication_leanigstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceapplication",
            name="leanigStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not Scheduled", "Not Scheduled"),
                    ("Scheduled", "Scheduled"),
                    ("Complete", "Complete"),
                ],
                default="Not Scheduled",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceapplication",
            name="testStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not Scheduled", "Not Scheduled"),
                    ("Scheduled", "Scheduled"),
                    ("Complete", "Complete"),
                ],
                default="Not Scheduled",
                max_length=100,
                null=True,
            ),
        ),
    ]
