# Generated by Django 4.1 on 2022-11-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0038_alter_serviceapplication_leanigstatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="driveRelated",),
    ]
