# Generated by Django 4.1 on 2022-11-16 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0019_rename_servicenonlicenceandprice_rcmodificationsandprice"),
        ("customer", "0041_serviceapplicationofnonlicence"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceApplicationOfNonLicence",
            new_name="ServiceApplicationOfRcModification",
        ),
    ]
