# Generated by Django 4.1 on 2022-11-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_licencemodificationsandprice"),
        ("customer", "0043_serviceapplicationoflicencemodification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceapplicationoflicencemodification",
            name="ServiceName",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.licencemodificationsandprice",
            ),
        ),
    ]
